name: CI

on: pull_request

env:
  VALKEY_HOSTNAME: valkey

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    container: swiftlang/swift:nightly-6.2-noble
    steps:
      - uses: actions/checkout@v4
      - run: swift format lint -r -p -s .
  test:
    runs-on: ubuntu-latest
    container: swift:latest
    services:
      valkey:
        image: valkey/valkey:latest
        ports:
          - 6379:6379
        options: --entrypoint valkey-server
    steps:
      - uses: actions/checkout@v4
      - run: swift build --build-tests
      - run: swift test --skip-build --parallel
